WIP: Use a timely restricted contact hash
systopia/de.systopia.newsletter pull request #21
Opened 2023-05-19 15:50 UTC by dontub

Use a timely restricted contact hash instead of CiviCRM's hash of the contact entity. Fixes #11.

2023-05-22 09:38 UTC, jensschuppe requested changes

2023-05-22 09:38 UTC, jensschuppe commented on api/v3/NewsletterSubscription/Get.php
> +    'title' => 'Contact hash',
Let's use the term *Contact Checksum* for explicitly indicating that it really is not the *Contact Hash*.

2023-05-22 09:38 UTC, jensschuppe commented on Civi/Newsletter/ContactHashService.php
> +class ContactHashService {
Let's rename that to something with *Checksum* instead of *Hash* for making it clear that it's a CiviCRM Contact Checksum instead of *the Contact Hash*.

2023-05-26 09:54 UTC, dontub commented on api/v3/NewsletterSubscription/Get.php
> +    'title' => 'Contact hash',
*Checksum* is now used instead of *Hash* in every place. This required an update step to change the placeholders in URLs. Additionally old hashes now still work, so URLs sent before an extension update will still work.

2023-06-22 08:05 UTC, jensschuppe approved these changes

2023-06-22 08:16 UTC, merged