initial implementation of weight feature for positioning of newslette…
systopia/de.systopia.newsletter pull request #36
Opened 2024-06-19 08:46 UTC by svenow

each field in contact section of form has an additional weight field. the weight can be set to values between 0 and 100. the default weight is 50.

a help text exists (when pressing the small blue question mark besides the weight input field) for a brief description about using weights.

what might be missing is setting the default weight-value for each field in setDefaultValues(), if weight has not been set yet. currently, this is not done and the weight value that is delivered via the api might be empty.

max and default weight values are defined as public static class variables, in order to access them in smarty-templates.

2024-06-19 11:21 UTC, jensschuppe requested changes

2024-06-19 11:21 UTC, jensschuppe commented on CRM/Newsletter/Form/Profile.php
> +        ))
Let's use short array syntax `[]` instead of `array()`.

2024-06-19 11:21 UTC, jensschuppe commented on CRM/Newsletter/Form/Profile.php
> +  public static $_form_field_weight_max = 100;
Those should be class constants.

2024-06-19 11:21 UTC, jensschuppe commented on CRM/Newsletter/Form/Profile.php
> +            )
Short array syntax, please.

2024-06-19 11:21 UTC, jensschuppe commented on CRM/Newsletter/Form/Profile.php
> +        }
Why have a max and min weight at all …?

2024-06-19 11:21 UTC, jensschuppe commented on l10n/de_DE/LC_MESSAGES/newsletter.po
> +
The phrase should end with a period `.`

2024-06-19 11:21 UTC, jensschuppe commented on l10n/de_DE/LC_MESSAGES/newsletter.po
> +
Also, `s/einen/ein` in the German translation

2024-06-19 11:21 UTC, jensschuppe commented on l10n/de_DE/LC_MESSAGES/newsletter.po
> +
Also, `s/to a integer/to an integer`

2024-06-19 11:21 UTC, jensschuppe commented on templates/CRM/Newsletter/Form/Profile.hlp
> +  <p>{ts domain="de.systopia.newsletter"}The effect of field positioning can be seen in the drupal view of this form.{/ts}</p>
The *Drupal* implementation should not be mentioned here, as the API is supposed to work for any implementation, not just the Drupal module.

2024-06-19 11:21 UTC, jensschuppe commented on templates/CRM/Newsletter/Form/Profile.hlp
> +  <p>{ts domain="de.systopia.newsletter"}The lower the weight value, the more the field will be shifted to the bottom of the form.{/ts}</p>
Actually, it's the other way around: higher weights cause fields to appear later in the form. Think things with *weight* sinking further down …

2024-06-19 11:21 UTC, jensschuppe commented on CRM/Newsletter/Form/Profile.php
> +  public static $_form_field_weight_default = 50;
This is not being enforced, right? Why have a default weight at all? Let's just have no weight by default.

2024-06-19 11:21 UTC, jensschuppe commented on CRM/Newsletter/Form/Profile.php
> +            )
Also, let's apply Code standards - there should be no space after negating `!`, but after a type cast `(int)` …

2024-07-16 07:12 UTC, svenow commented
New commits should have resolved all previous review remarks.

- the implicit default weight for all fields is 0
- no explicit min or max weight values are used
- as smaller/more negative a weight becomes, as higher the corresponding field moves up to the top of the form
- as larger/more positive a weight becomes, as lower the corresponding field moves down to the bottom of the form

2024-07-16 10:14 UTC, jensschuppe requested changes
Just a code review, did not test.

2024-07-16 10:14 UTC, jensschuppe commented on CRM/Newsletter/Form/Profile.php
> +          && filter_var($fieldValue, FILTER_VALIDATE_INT) === false
`s/false/FALSE` according to CiviCRM Code standards.

2024-07-16 11:45 UTC, jensschuppe approved these changes

2024-07-16 12:25 UTC, merged